# **Numpy**

## array（陣列）vs. list（序列）

In [1]:
l = [1, 2, 3]
#l +=1

In [2]:
import numpy as np
L = np.array(l)
print(L)
L += 1
print(L)

[1 2 3]
[2 3 4]


In [3]:
for i in range(len(l)):
    l[i] +=1
print(l)

[2, 3, 4]


## 建立 array

### 一維陣列
1. 先建立一個清單 list
2. 利用這個清單 List 與 元組 Tuple 去建立陣列
3. 之後可以運用索引的方式更改指定陣列的值

In [4]:
lst = [1, 4, 8, 10]
arr = np.array(lst)
print(arr)
arr[2] = -2
print(arr)

[ 1  4  8 10]
[ 1  4 -2 10]


### 多維陣列
- 使用巢狀清單去建立多維陣列
- 有幾個 中括弧[] 就代表有幾維陣列

In [5]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# 要記得「先看 row, 再看 column」
arr2[0,0] = -10
print(arr2)
print(arr2[0,0], arr2[0,1], arr2[0,2])
print(arr2[1,0], arr2[1,1], arr2[1,2])

[[1 2 3]
 [4 5 6]]
[[-10   2   3]
 [  4   5   6]]
-10 2 3
4 5 6


## 建立指定元素型態的陣列

In [6]:
arr3 = np.array([1,2,3,4,5], int)
print(arr3)

[1 2 3 4 5]


In [7]:
arr4 = np.array([1,2,3,4,5], float)
print(arr4)
arr5 = np.array((1,2,3,4,5), float)
print(arr5)

[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]


## 快速建立陣列的放法

In [8]:
a = np.arange(5)
print(a)
a1 = np.arange(1, 6)
print(a1)
a2 = np.arange(1, 6, 2) # 最後一個數字，代表變動方向與量
print(a2)

[0 1 2 3 4]
[1 2 3 4 5]
[1 3 5]


In [9]:
b = np.zeros(2)
print(b)
b1 = np.zeros((2,2))
print(b1)

[0. 0.]
[[0. 0.]
 [0. 0.]]


In [10]:
c = np.ones(2)
print(c)
c1 = np.ones((2,3))
print(c1)

[1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


## 陣列維度轉換

In [11]:
d = np.arange(16)
print(d)
d1 = d.reshape((2,8))
print(d1)
d2 = d.reshape((4,4))
print(d2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## 走訪陣列元素
### 一維陣列：for 迴圈
### 二維陣列：for 巢狀迴圈

In [12]:
e = np.arange(5)
print(e)
for ele in e:
    print(ele, end = " ")

[0 1 2 3 4]
0 1 2 3 4 

In [13]:
f = np.array([[1,2], [3,4], [5,6]])
print(f)

for ele in f:
    print(ele, end= " ")
    
print()    

for ele in f:
    for item in ele:
        print(item, end= " ")

[[1 2]
 [3 4]
 [5 6]]
[1 2] [3 4] [5 6] 
1 2 3 4 5 6 

## 使用亂數函數產生陣列元素值

In [14]:
g = np.random.rand()
print(g)
g1 = np.random.randint(0, 100)
print(g1)
g2 = np.random.random()
print(g2)
np.random.seed(5)
print(np.random.rand())

0.2575640826119264
64
0.0966071923051175
0.22199317108973948


## 向量運算

In [15]:
h = np.array([1,2,3])
print(h)

i = 5  # i 是個純量
print(i)

[1 2 3]
5


In [16]:
# h1 = h + i
print(h)
h1 = h + i
print(h1)
h2 = h - i
print(h2)
h3 = h * i
print(h3)
h4 = h / i
print(h4)

[1 2 3]
[6 7 8]
[-4 -3 -2]
[ 5 10 15]
[0.2 0.4 0.6]


In [17]:
# 相同維度的向量才可以相加
j = np.arange(2, 5)
print("h =",h)
print("j =",j)
h5 = h + j
print(h5)
h6 = h - j
print(h6)
h7 = h * j
print(h7)
h8 = h / j
print(h8)

h = [1 2 3]
j = [2 3 4]
[3 5 7]
[-1 -1 -1]
[ 2  6 12]
[0.5        0.66666667 0.75      ]


#### 點積運算 dot product: 把相對應的向量相乘後的結果全部加總起來

In [18]:
print("h =",h)
print("j =",j)
print("h * j =", h7)

h9 = h.dot(j)
print(h9)

h = [1 2 3]
j = [2 3 4]
h * j = [ 2  6 12]
20


## 向量的長度: 使用 numpy 的 linalg module 的 norm method 處理

範例：假設今天住家位於座標（0,0），公園座標（1,3），商店（2,1），公司（4,4）

In [19]:
# 住家到公園的距離
park = np.array([1,3])
distance_park = np.linalg.norm(park)
print(distance_park)

3.1622776601683795


In [20]:
# 從商店到公司的距離
store = np.array([2,1])
office = np.array([4,4])
store_office = office - store
print(store_office)
distance_store_office = np.linalg.norm(store_office)
print(distance_store_office)

[2 3]
3.605551275463989


## 切割一維陣列的元素 
* array[start: end: step]

In [21]:
k = np.arange(1,10)
print("k =", k)

k1, k2, k3 = k[1:3], k[:4], k[3:]
print(k1, k2, k3)

k4, k5, k6 = k[2:9:3], k[::2], k[::-1]
print(k4, k5, k6)

k = [1 2 3 4 5 6 7 8 9]
[2 3] [1 2 3 4] [4 5 6 7 8 9]
[3 6 9] [1 3 5 7 9] [9 8 7 6 5 4 3 2 1]


## 矩陣運算

In [31]:
l = np.array([[1,2],[4,5]])
print(l)
print(i)

[[1 2]
 [4 5]]
5


In [32]:
l1 = l + i
print(l1)
l2 = l - i
print(l2)
l3 = l * i
print(l3)
l4 = l / i
print(l4)

[[ 6  7]
 [ 9 10]]
[[-4 -3]
 [-1  0]]
[[ 5 10]
 [20 25]]
[[0.2 0.4]
 [0.8 1. ]]


In [33]:
m = np.array([[7,8], [10,11]])
print(m)

[[ 7  8]
 [10 11]]


In [34]:
l5 = l + m
print(l5)
l6 = l - m
print(l6)
l7 = l * m
print(l7)
l8 = l / m
print(l8)

[[ 8 10]
 [14 16]]
[[-6 -6]
 [-6 -6]]
[[ 7 16]
 [40 55]]
[[0.14285714 0.25      ]
 [0.4        0.45454545]]


#### 矩陣的點積運算 Dot product: 兩個矩陣對應元素的列和行的乘積和
- 必須是正方形矩陣 (n*n) 才行

In [36]:
l9 = l.dot(m)
print(l9)

[[27 30]
 [78 87]]


## 切割二維陣列的元素 
* array[start: end: step, start2: end2: step2]

In [40]:
n = np.arange(11, 36)
print(n)
n = n.reshape(5,5)
print(n)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [46]:
n1 = n[0, 1:4]
print(n1)
n2 = n[1:4, 0]
print(n2)
n3 = n[:2, 1:3]
print(n3)
n4 = n[:, 1]
print(n4)
n5 = n[::2, ::2]
print(n5)

[12 13 14]
[16 21 26]
[[12 13]
 [17 18]]
[12 17 22 27 32]
[[11 13 15]
 [21 23 25]
 [31 33 35]]


### 使用進階索引 (Index) 取出元素

In [50]:
o = np.arange(1,10)
print(o)
o1 = o[[1,3,5,7]]
print(o1)

[1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [51]:
o2 = (o % 2 == 0)
print(o2)

[False  True False  True False  True False  True False]


## 陣列平坦化: ravel()

In [54]:
print(l)
l10 = l.ravel()
print(l10)
l11 = np.ravel(l)
print(l11)

[[1 2]
 [4 5]]
[1 2 4 5]
[1 2 4 5]


## 交換陣列維度: .T or transpose()

In [57]:
print(l)
l12 = l.T
print(l12)
l13 = l.transpose()
print(l13)

[[1 2]
 [4 5]]
[[1 4]
 [2 5]]
[[1 4]
 [2 5]]


## 新增陣列維度: np.newaxis

In [64]:
p = np.arange(0,3)
print(p)
p1 = p[:, np.newaxis]
print(p1)
print(p1.shape)

[0 1 2]
[[0]
 [1]
 [2]]
(3, 1)


## 陣列複製: copy()
* copy 在陣列中很重要！他可以保留原始值，不管我們後續對複製的陣列做什麼更動，都不影響原始陣列！！

In [72]:
q = p.copy()
print(q)
print(p)
q[1] = -2
print(q)
print(p)

[  0 100   2]
[  0 100   2]
[ 0 -2  2]
[  0 100   2]


In [75]:
id(p)

4588115632

In [76]:
id(q)

4604525424

In [69]:
# 直接用等號指派變數的話，我們後續只要對其中一個變數做更動，另一個也會一起變更，因為他們在程式中其實是被定義為同個變數
r = p
print(r)
print(p)
r[1] = 100
print(r)
print(p)

[0 1 2]
[0 1 2]
[  0 100   2]
[  0 100   2]


In [77]:
id(r)

4588115632

## 其他陣列操作

In [80]:
print(q)
q.fill(4)
print(q)

[ 0 -2  2]
[4 4 4]


### 連接陣列：concatenate()

In [82]:
pq = np.concatenate((p,q))
print(pq)

[  0 100   2   4   4   4]


In [88]:
print(m)
print(l)

[[ 7  8]
 [10 11]]
[[1 2]
 [4 5]]


In [87]:
# axis = 0，連接在 row 下方
ml1 = np.concatenate((m, l), axis = 0)
print(ml1)
print()
# axis =1，連接在 column 後方
ml2 = np.concatenate((m, l), axis = 1)
print(ml2)

[[ 7  8]
 [10 11]
 [ 1  2]
 [ 4  5]]

[[ 7  8  1  2]
 [10 11  4  5]]


## 陣列廣播 Broadcasting

In [94]:
s = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(s)
print("s 矩陣的形狀：",s.shape)
print()
t = np.array([1,0,1])
print(t)
print("t 矩陣的形狀：",t.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
s 矩陣的形狀： (4, 3)

[1 0 1]
t 矩陣的形狀： (3,)


In [95]:
st = s + t
print(st)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


## Numpy 其他函數運算

In [98]:
x = np.arange(0, 100, 10, dtype=float)
print(x)

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]


In [105]:
index = np.random.randint(0,len(x),5)  # 讓程式隨機抓五個出來！
print(index)
print(x[index])

[0 5 0 0 4]
[ 0. 50.  0.  0. 40.]


### 指定不同維度的計算

In [107]:
y = np.arange(0, 10).reshape(2,5)
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [112]:
print(np.sum(y))

45


In [121]:
print(np.sum(y, axis = 0)) # axis = 0 縱向求合
print(np.sum(y, axis = 1)) # axis = 1 橫向求合

[ 5  7  9 11 13]
[10 35]


In [125]:
# mean 算術平均
print(np.mean(y, axis = 0)) 

# average 算加權平均
weight = [0.3, 0.7]
print(np.average(y, axis =0, weights=weight))

[2.5 3.5 4.5 5.5 6.5]
[3.5 4.5 5.5 6.5 7.5]


In [134]:
z = np.array([0,4,3,3,8,4,7,3,1,7])
print(z)

print(np.argmax(z)) # 最大值的索引

print(np.where(z<5, 0, 2))

z1 = np.piecewise(z, [z<4, z>7], [lambda z:z**2, lambda z:z**3])
print(z1)

[0 4 3 3 8 4 7 3 1 7]
4
[0 0 0 0 2 0 2 0 0 2]
[  0   0   9   9 512   0   0   9   1   0]
